# Generated by Django 5.1.6 on 2025-02-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentData', '0002_alter_studentdata_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
